### PR TITLE
GriefPrevention support

### PR DESCRIPTION
**Pull request by DevJul1an**
Adds support for GriefPrevention (https://www.spigotmc.org/resources/griefprevention.1884/)

### CODE REVIEW

**Comment by Falseee** [comment]
Tested in older (minecraft) versions ?

**Comment by DevJul1an** [comment]
Tested with the following versions:

Spigot 1.12.2 - GriefPrevention 16.8
Spigot 1.11.2 - GriefPrevention 16.7.1
Spigot 1.10.2 - GriefPrevention 16.4
Spigot 1.9.4 - GriefPrevention 14.7
Spigot 1.8.8 - GriefPrevention 13.9.1

**Comment by Falseee** [comment]
I will test and merge it on the week end, currently im busy.

**Comment by Falseee** [comment]
Thank you !

**Pull request merged**
